catalog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    re_path(r'^books/$', views.BookListView.as_view(), name='books'),
    re_path(r'^book/(?P<pk>\d+)/$',
            views.BookDetailView.as_view(), name='book-detail'),
    re_path(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
    re_path(r'^authors/(?P<pk>\d+)/$',
            views.AuthorDetailView.as_view(), name='author-detail'),
    re_path(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(),
            name='my-borrowed'),
    re_path(r'^book/(?P<pk>[-\W]+)/renew/$',
            views.renew_book_libration, name='renew_book_libration'),
    re_path(r'^author/create/$', views.AuthorCreate.as_view(),
            name='author_create'),
    re_path(r'^author/(?P<pk>\d+)/update/$', views.AuthorUpdate.as_view(),
            name='author_update'),
    re_path(r'^author/(?P<pk>\d+)/delete/$', views.AuthorDelete.as_view(),
            name='author_delete')
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [path('accounts/', include('django.contrib.auth.urls'))]

catalog/models.py
import uuid
from datetime import date
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.


class Genre(models.Model):
    """Genre class"""
    name = models.CharField(
        max_length=200, help_text="Enter a book genre (e.g. Science Fiction, Ferench Poetry etc .)")

    def __str__(self):
        return self.name


class Book(models.Model):
    """Book Class"""
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(
        max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN', max_length=13, help_text="13 Character")
    genre = models.ManyToManyField(
        Genre, help_text="Select a genre for this book")

    def __str__(self):
        """member description"""
        return self.title

    def get_absolute_url(self):
        """redirect link in class"""
        return reverse('catalog:book-detail', args=[str(self.id)])

    def display_genre(self):
        """display range of Genre"""
        return ','.join([genre.name for genre in self.genre.all()[:3]])


# display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    """BookInstance class"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved')
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS,
                              blank=True, default='m', help_text='Book availablity')
    borrower = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        """ member description"""
        return '%s (%s)' % (self.id, self.book.title)

    @property
    def is_overdue(self):
        """check if book is overdue in date"""
        if self.due_back and date.today() > self.due_back:
            return True
        return False


class Author(models.Model):
    """Author class"""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
        """redirect link in class"""
        return reverse('catalog:author-detail', args=[str(self.id)])

    def __str__(self):
        """member description"""
        return '%s, %s' % (self.last_name, self.first_name)

catalog/forms.py
from datetime import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

# The Form for renewing Book


class RenewBookForm(forms.Form):
    """
    Class Form for renewing Book
    """
    renewal_date = forms.DateField(
        help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        """
        Clean function for Validating renewal date
        """
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead'))

        return data

catalog/views.py
from datetime import datetime
from django.shortcuts import render, reverse, get_object_or_404
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import permission_required
from django.urls import reverse_lazy
from .forms import RenewBookForm
from . import models


class Index(generic.TemplateView):
    """
    Index TemplateView
    """
    template_name = 'catalog/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['num_books'] = models.Book.objects.all().count()
        context['num_instances'] = models.BookInstance.objects.all().count()
        context['num_instances_available'] = models.BookInstance.objects.filter(
            status__exact='a').count()
        context['num_authors'] = models.Author.objects.all().count()
        return context


class BookListView(generic.ListView):
    """
    ListlView Class for Showing Books
    """
    template_name = 'catalog/book_list.html'
    # context_object_name = 'book_list '
    model = models.Book


class BookDetailView(generic.DetailView):
    """
    DetailView Class for Showing Book Detail
    """
    template_name = 'catalog/book_detail.html'
    context_object_name = 'book'
    model = models.Book


class AuthorListView(generic.ListView):
    """
    ListlView Class for Showing Authors
    """
    template_name = 'catalog/author_list.html'
    model = models.Author


class AuthorDetailView(generic.DetailView):
    """
    DetailView Class for an Author
    """
    model = models.Author
    template_name = 'catalog/author_detail.html'


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """
    ListView Class for Showing LoanedBook by User
    """
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    model = models.BookInstance
    paginate_by = 10

    def get_queryset(self):
        """
        Quering function for Loaned Books
        """
        return models.BookInstance.objects.filter(
            borrower=self.request.user).filter(status__exact='o').order_by('due_back')


@permission_required('catalog.can_mark_returned')
def renew_book_libration(request, pk):
    """
    View function for renewing a specific BookInstance by libration
    """
    book_inst = get_object_or_404(models.BookInstance, pk=pk)

    if request.method == 'POST':
        form = RenewBookForm[request.POST]

        if form.is_valid():
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()
            return HttpResponseRedirect(reverse('catalog:my-borrowed'))
        else:
            proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
            form = RenewBookForm(
                initial={'renewal_date': proposed_renewal_date, })

    return render(request, 'catalog/book_renew_libration.html',
                  {'form': form, 'bookinst': book_inst})


class AuthorCreate(generic.CreateView):
    """create Author"""
    model = models.Author
    fields = '__all__'
    initial = {'date_of_birth': '01/01/2019', }


class AuthorUpdate(generic.UpdateView):
    """update Author"""
    model = models.Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']


class AuthorDelete(generic.DeleteView):
    """ddelete Author"""
    model = models.Author
    success_url = reverse_lazy('catalog:authors')

# def index(request):
#     num_books=models.Book.objects.all().count()
#     num_instances=models.BookInstance.objects.all().count()
#     num_instances_available=models.BookInstance.objects.filter(status__exact='a').count()
#     num_authors=models.Author.objects.all().count()
#
#     return render(request, 'catalog/index.html', context={
#     'num_books':num_books,
#     'num_instances' : num_instances,
#     'num_instances_available' : num_instances_available,
#     'num_authors' : num_authors
#     })

catalog/templates/catalog/author_confirm_delete.html
{% extends "catalog/base_generic.html" %}

{% block content %}
<h1>Delete Author</h1>
<p>Are you sure you want to delete the author: {{ author }}?</p>
<form action="" method="POST">
  {% csrf_token %}

  <input type="submit" action="" value="yes, delete.">
</form>
{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "catalog/base_generic.html" %}

{% block content %}
<p>Author first name: {{ author.first_name  }}</p>
<p>Author last name: {{ author.last _name  }}</p>
<p>date of birth: {{ author.date_of_birth  }}</p>
<p>date of death: {{ author.date_of_death  }}</p>
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "catalog/base_generic.html" %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit">
</form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "catalog/base_generic.html" %}

{% block content %}
{% for author in author_list %}
<h3>{{ author.last_name }}</h3>
<p>Author first name: {{ author.first_name  }}</p>
<p>date of birth: {{ author.date_of_birth  }}</p>
<p>date of death: {{ author.date_of_death  }}</p>
<hr>
{% endfor %}
{% endblock %}

catalog/templates/catalog/base_generic.html
<!DOCTYPE html>
<html lang="en">

  <head>
    {% block title %} <title>Local Library</title> {% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapies.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'catalog/styles.css' %}">
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
          <ul class="sidebar-nav">
            <li><a href="{% url 'catalog:index' %}">Home</a></li>
            <li><a href="{% url 'catalog:books' %}">All books</a></li>
            <li><a href="{% url 'catalog:authors' %}">All authors</a></li>
            <li><a href="/admin/">Admin Page</a></li>
            <li><a href="{% url 'catalog:my-borrowed' %}">My Borrowed</a></li>
            {% if user.is_authenticated %}
            <li>User: {{ user.get_username }}</li>
            <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>

            {% endif %}
          </ul>
          {% endblock %}
        </div>
        <div class="col-sm-10">
          {% block content %} {% endblock %}
        </div>
      </div>
    </div>
  </body>

</html>

catalog/templates/catalog/book_detail.html
{% extends "catalog/base_generic.html" %}

{% block content %}
<h1>Title: {{ book.title }}</h1>
<p><strong>Author:</strong> <a href="">{{ book.author }}</a> </p>
<p><strong>Summary:</strong> {{ book.summary }}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p>
{# <p><strong>Language:</strong> {{ book.language }}</p> #}
<p><strong>Genre:</strong>
  {% for genre in book.genre.all %}
  {{ genre }}
  {% if not forloop.last %},
  {% endif %}
  {% endfor%}
</p>
{% endblock %}

catalog/templates/catalog/book_list.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% if book_list %}
<ul>
  {% for book in book_list %}
  <li>
    <a href="{ book.get_absolute_url }">{{ book.title }}</a> ({{ book.author }})
  </li>
  {% endfor %}
</ul>
{% else %}
{% bootstrap_alert "There are no books in the library." alert_type='danger' %}
{% endif %}

catalog/templates/catalog/book_renew_libration.html
{% extends "catalog/base_generic.html" %}
{% block content %}
<h1>Renew: {{ bookinst.book.title }}</h1>
<p>Borrower: {{bookinst.borrower }} </p>
<p {% if bookinst.is_overdue %} class="text-danger" {% endif %}>Due date:{{bookinst.due_back}}</p>

<form action="" method="POST">
  {% csrf_token %}
  <table>
    {{ form }}
  </table>
  <input type="submit" value="Submit">
</form>

{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "catalog/base_generic.html" %}

{% block content %}
<h1>Borrowed books</h1>
{% if bookinstance_list %}
<ul>
  {% for bookinst in bookinstance_list %}
  <li class="{% if bookinst.is_overdue %} text-danger {% endif %}">
    <a href="{% url 'catalog:book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }})
  </li>
  {% endfor %}
</ul>
{% else %}
<p>There are no books borrowed.</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/index.html
{% extends "catalog/base_generic.html" %}

{% block content %}
<h1>Local Library Home</h1>
  <p>Welcome to <em>LocalLibrary</em>, a very basic Django website. </p>

<h2>Dynamic Content</h2>

  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{num_books }}</li>
    <li><strong>Copies:</strong> {{num_instances }}</li>
    <li><strong>Copies available:</strong> {{num_instances_available }}</li>
    <li><strong>Authors:</strong> {{num_authors }}</li>
  </ul>
{% endblock %}